
// 해당 코드는 폰트와 metadata 관련 코드
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <div>
      <p>(숙제) 현대카드 무이자이벤트 중</p> 
      {children}
    </div>
  );
}
