import Link from "next/link";
import "./globals.css";

import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// (중요) 가장 바깥쪽의 layout.js의 함수 RootLayout({ children })의 children은 가장 바깥에 작성한 page.js를 의미하고 레이아웃이 랜더링 될 위치를 의미 (= react의 App 컴포넌트 역할)
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body>
        <div className="navbar">
          <Link href="/">Home</Link>
          <Link href="/list">List</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
